#if !defined _GCSAMPLESCREEN_HPP_
#define _GCSAMPLESCREEN_HPP_
#include "genifa.h"
#include "GWin.h"
#include "GCBaseWindow.hpp"
#include "GCScreen.hpp"
#include "string.h"

//{{OBJECT_TYPE
#define GHOMESCREEN1 GUSERWINDOW_BASE+0
#define GPREMACH1 GUSERWINDOW_BASE+1
#define GDURINGMACH GUSERWINDOW_BASE+2
#define GPOSTMACH GUSERWINDOW_BASE+3
#define GDIAGNOSIS GUSERWINDOW_BASE+4
#define GMAINTE GUSERWINDOW_BASE+5
#define GGCODE GUSERWINDOW_BASE+6
#define GMCODE GUSERWINDOW_BASE+7
#define GCUTPARA GUSERWINDOW_BASE+8
#define GDRILLSEL GUSERWINDOW_BASE+9
#define GMAGVIEW2 GUSERWINDOW_BASE+10
#define GMAGLIST GUSERWINDOW_BASE+11
#define GLOADTYPE GUSERWINDOW_BASE+12
#define GTREND GUSERWINDOW_BASE+13
#define GMCCOND GUSERWINDOW_BASE+14
#define GMCCONDSEL GUSERWINDOW_BASE+15
#define GDAILYCHK GUSERWINDOW_BASE+16
#define GMONTHLYCHK GUSERWINDOW_BASE+17
#define GQUTRLYCHK GUSERWINDOW_BASE+18
#define GPREVSCREEN GUSERWINDOW_BASE+19
#define GVERSION1 GUSERWINDOW_BASE+20
#define GVERSION2 GUSERWINDOW_BASE+21
#define GINPUT1 GUSERWINDOW_BASE+22
#define GINPUT2 GUSERWINDOW_BASE+23
#define GOUTPUT1 GUSERWINDOW_BASE+24
#define GOUTPUT2 GUSERWINDOW_BASE+25
#define GBITS1 GUSERWINDOW_BASE+26
#define GBITS2 GUSERWINDOW_BASE+27
#define GBITS3 GUSERWINDOW_BASE+28
#define GBITS4 GUSERWINDOW_BASE+29
#define GBITS5 GUSERWINDOW_BASE+30
#define GBITS6 GUSERWINDOW_BASE+31
#define GBITS7 GUSERWINDOW_BASE+32
#define GBITS8 GUSERWINDOW_BASE+33
#define GCYCLETIME GUSERWINDOW_BASE+34
#define GDWNTIMEANA GUSERWINDOW_BASE+35
#define GDWNTIMEHIS GUSERWINDOW_BASE+36
#define GDAILYUTI GUSERWINDOW_BASE+37
#define GDAILUTIHIS GUSERWINDOW_BASE+38
#define GOEER GUSERWINDOW_BASE+39
#define GOEEHIS GUSERWINDOW_BASE+40
#define GOPERSET GUSERWINDOW_BASE+41
#define GALARMHELP GUSERWINDOW_BASE+42
#define GCUTOMETER1 GUSERWINDOW_BASE+43
#define GBACKUP GUSERWINDOW_BASE+44
#define GCALCULATOR GUSERWINDOW_BASE+45
#define GDOWNTIMEDATA GUSERWINDOW_BASE+46
#define GLOCKWINDOW GUSERWINDOW_BASE+47
#define GHELPWINDOW1 GUSERWINDOW_BASE+48
#define GDOWNTIMEDATAM GUSERWINDOW_BASE+49
#define GHELPWINDOW1HELPFRAME GUSERWINDOW_BASE+50
#define GHELPWINDOW1HELPFRAMEPANEL000 GUSERWINDOW_BASE+51
#define GHELPWINDOW1HELPFRAMEPANEL001 GUSERWINDOW_BASE+52
//}}OBJECT_TYPE

#ifdef NO_WINDOWS
class GCSampleScreenCosmos_M80_Project_D : public GCScreen
{
public:
	//{{PUBLIC_METHOD
	GCSampleScreenCosmos_M80_Project_D();
	virtual ~GCSampleScreenCosmos_M80_Project_D();

	virtual short Create( GBaseObject *pParent );
	virtual GPropertyInfo* GetPropertyInfo(const GBaseWindowProperty* pImport, unsigned short* pGPropertyInfoCnt);
	//}}PUBLIC_METHOD

protected:
	//{{PROTECTED_METHOD
	GCDefMP()
	GCDefCBMP()					/* コールバックメッセージ処理　	*/
	GCDefCreateInstance()
	GCDefShowPanel()
	GCDefCreateGWindow()
	GCDefModalGWindow()
	GCDefLoadGWindow()
	//}}PROTECTED_METHOD
	
};

#else//NO_WINDOWS
class GCSampleScreen : public GCScreen
{
public:
	//{{PUBLIC_METHOD
	GCSampleScreen();
	virtual ~GCSampleScreen();

	virtual short Create( GBaseObject *pParent );
	virtual GPropertyInfo* GetPropertyInfo(const GBaseWindowProperty* pImport, unsigned short* pGPropertyInfoCnt);
	//}}PUBLIC_METHOD

protected:
	//{{PROTECTED_METHOD
	GCDefMP()
	GCDefCBMP()					/* コールバックメッセージ処理　	*/
	GCDefCreateInstance()
	GCDefShowPanel()
	GCDefCreateGWindow()
	GCDefModalGWindow()
	GCDefLoadGWindow()
	//}}PROTECTED_METHOD
	
};

#endif//NO_WINDOWS
#endif /* _GCSAMPLESCREEN_HPP_ */
